version: '3.1'

services:
#  fastapi:
#    restart: always
#    build: .
#    ports:
#      - "8000:8000"
#
#  celery:
#    restart: always
#    build: .

  postgres:
    restart: always
    image: postgres:13.0
    env_file: .env
    environment:
        - POSTGRES_DB=${POSTGRES_DBNAME}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASS}
    volumes:
        - postgresql-volume:/var/lib/postgresql/data
    ports:
        - "5432:5432"


volumes:
  postgresql-volume: